body:
  - type: textBlock
    attributes:
      name: description
      description: >
        Search & launch your Playnite library.
  - type: input
    attributes:
      name: playnite_path
      label: 'Playnite Directory:'
      description: Location of Playnite folder or database file.
  - type: textBlock
    attributes:
      name: description
      description: >
        Path should be either your Playnite install directory or the database file. 
        Example: `C:\Users\%USERNAME%\AppData\Roaming\Playnite` or `%APPDATA%\Playnite\ExtensionsData\FlowLauncherExporter`.
  - type: checkbox
    attributes:
      name: hide_uninstalled
      label: 'Hide Uninstalled:'
      defaultValue: "true"
      description: Hides uninstalled from default results
  - type: checkbox
    attributes:
      name: show_hidden
      label: 'Show Hidden:'
      defaultValue: "false"
      description: Show hidden games in default results