name: "PR-Tester"
on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
  workflow_dispatch:
env:
  PYTHON_VER: 3.8
jobs:
  deps:
    name: "Test"
    runs-on: windows-latest
    steps:
      - name: Load Cache
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: .\Flow-Launcher-Setup.exe
          key: ${{ runner.os }}-flow-
      - name: Download Flow Launcher
        run: |
          if (-Not (Test-Path .\Flow-Launcher-Setup.exe))
          {
            curl.exe -L -o Flow-Launcher-Setup.exe "https://github.com/Flow-Launcher/Flow.Launcher/releases/latest/download/Flow-Launcher-Setup.exe"
          }
      - name: Install Flow Launcher
        run: .\Flow-Launcher-Setup.exe
        shell: cmd
      - name: Checkout Plugin Repo
        uses: actions/checkout@v2
        with:
          path: ${{github.event.repository.name}}
      - name: Move checkout repo
        run: |
          $repo_path = Join-Path -Path $pwd -ChildPath ${{github.event.repository.name}}
          $plugin_path = Join-Path -Path $env:APPDATA -ChildPath 'FlowLauncher' | Join-Path -ChildPath 'Plugins' | Join-Path -ChildPath ${{github.event.repository.name}}
          New-Item -ItemType SymbolicLink -Path $plugin_path -Target $repo_path
          echo "PLUGIN_PATH=$plugin_path" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          cd ${{ env.PLUGIN_PATH }}
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r ./requirements.txt -t ./lib
      - name: Get Plugin's version
        id: exe
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: '${{ env.PLUGIN_PATH }}/plugin.json'
          prop_path: 'ExecuteFileName'
      - name: Test Run
        run: |
          cd ${{ env.PLUGIN_PATH }}
          echo ${{ env.PLUGIN_PATH }}
          echo ${{steps.exe.outputs.prop}}
          python ${{steps.exe.outputs.prop}}

